steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us.gcr.io/$PROJECT_ID/auction-manager', '-t', 'us.gcr.io/$PROJECT_ID/auction-manager:$COMMIT_SHA', '-f', './compose/production/django/Dockerfile', '.' ]
images:
- 'us.gcr.io/$PROJECT_ID/auction-manager:$COMMIT_SHA'
- 'us.gcr.io/$PROJECT_ID/auction-manager:latest'
timeout: 3600s
