version: '2'

services:
  django-dev:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
    command: /start.sh
