# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=140)),
                ('onsite_pickup', models.BooleanField(default=True)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_point', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('L', 'Live'), ('S', 'Silent')], default='S', max_length=1)),
                ('lot', models.IntegerField(db_index=True, unique=True)),
                ('short_desc', models.CharField(blank=True, help_text='A short description for a slide or card', max_length=140)),
                ('description', models.TextField(blank=True, help_text='A long description suitable for printed text (e.g. website, program)')),
                ('title', models.CharField(max_length=50)),
                ('restrictions', models.CharField(blank=True, max_length=140)),
                ('FMV', models.PositiveIntegerField(null=True)),
                ('predicted_sale', models.PositiveIntegerField(null=True)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to='uploads/')),
                ('reviewed', models.BooleanField(default=False, help_text='The lot has been reviewed for accuracy by an auction chair')),
                ('received', models.BooleanField(default=False, help_text='The auction committee is in possession of all items in the lot')),
                ('confirmed', models.BooleanField(default=False, help_text='The items has been reviewed complete and available on-site for sale')),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=50)),
                ('size', models.CharField(default='750 ml', max_length=10)),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('rating', models.CharField(blank=True, max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Lot'),
        ),
    ]
