# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-22 21:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('abbr', models.CharField(help_text='Abbreviation for use in application', max_length=8, unique=True)),
                ('date', models.DateField()),
                ('contact_email', models.EmailField(max_length=255)),
                ('main_image', models.ImageField(null=True, upload_to='')),
                ('auction_primary', models.ForeignKey(help_text='Person to list on the auction receipt as follow-up contact for any issues', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('chairmen', models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.PositiveIntegerField(help_text='The entry number of the donation form')),
                ('auction', models.ForeignKey(help_text='The auction currently associated with the donation', on_delete=django.db.models.deletion.CASCADE, to='auction.Auction')),
            ],
        ),
        migrations.CreateModel(
            name='DonationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Short description of the item for display and receipt', max_length=140)),
                ('onsite_pickup', models.BooleanField(default=True)),
                ('contact_name', models.CharField(help_text='Contact name for bidder questions', max_length=50)),
                ('contact_point', models.CharField(help_text='Contact point (e.g., phone or email) for contact', max_length=50)),
                ('location', models.CharField(choices=[('OFFICE', 'Guardsmen Office'), ('SFWC', 'SF Wine Center'), ('OTHER', 'Other')], default='OTHER', help_text='Where the item is currently located', max_length=40)),
                ('location_notes', models.CharField(max_length=255, null=True)),
                ('donation', models.ForeignKey(help_text='The donation form submitted for this item', null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Donation')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('type', models.CharField(choices=[('L', 'Live'), ('S', 'Silent')], default='S', max_length=1)),
                ('category', models.CharField(choices=[('W', 'Wine'), ('G', 'Golf'), ('E', 'Experiences'), ('O', 'Other'), ('S', 'Super Silent')], default='O', max_length=1)),
                ('title', models.CharField(max_length=50)),
                ('short_desc', models.CharField(blank=True, help_text='A short description for a slide or card', max_length=140)),
                ('description', models.TextField(blank=True, help_text='A long description suitable for printed text (e.g. website, program)')),
                ('restrictions', models.CharField(blank=True, max_length=140)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('FMV', models.PositiveIntegerField(null=True)),
                ('pickup_instructions', models.TextField(blank=True, help_text='Additional redemption instructions for the lot')),
                ('item_description_override', models.TextField(blank=True, help_text='A HTML-enabled description of the items to override the default rendering')),
                ('start_bid', models.PositiveIntegerField(null=True)),
                ('min_raise', models.PositiveIntegerField(null=True)),
                ('predicted_sale', models.PositiveIntegerField(null=True)),
                ('aquisition_cost', models.PositiveIntegerField(default=0)),
                ('actual_sale', models.PositiveIntegerField(null=True)),
                ('tax_percentage', models.FloatField(default=1, help_text='The percentage of the lot that is taxable (i.e., goods)')),
                ('complete', models.BooleanField(default=False, help_text='The lot description and items are complete')),
                ('confirmed', models.BooleanField(default=False, help_text='The items has been reviewed complete and available on-site for sale')),
                ('notes', models.TextField(blank=True, help_text='Internal notes on the lot')),
                ('auction', models.ForeignKey(help_text='The auction this lot is associated with', on_delete=django.db.models.deletion.CASCADE, to='auction.Auction')),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=50)),
                ('size', models.CharField(default='750 ml', max_length=10)),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('rating', models.CharField(blank=True, max_length=10)),
                ('confirmed', models.BooleanField(default=False)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Lot'),
        ),
        migrations.AddField(
            model_name='donation',
            name='source_form',
            field=models.ForeignKey(help_text='The donation form', null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.DonationForm'),
        ),
        migrations.AddField(
            model_name='auction',
            name='donation_form',
            field=models.ForeignKey(help_text='The donation form associated with the auction', null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.DonationForm'),
        ),
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together=set([('auction', 'lot_number')]),
        ),
    ]
