# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-22 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='donation_form',
            field=models.ForeignKey(blank=True, help_text='The donation form associated with the auction', null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.DonationForm'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
