# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-22 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20171022_1452'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donation',
            unique_together=set([('source_form', 'form_id')]),
        ),
    ]
