# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20170301_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='item_description_override',
            field=models.TextField(blank=True, help_text='A text description of the items to override the default'),
        ),
        migrations.AddField(
            model_name='lot',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes on the lot'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
