# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-23 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20171022_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='form_id',
            new_name='form_entry_number',
        ),
        migrations.AlterUniqueTogether(
            name='donation',
            unique_together=set([('source_form', 'form_entry_number')]),
        ),
    ]
