# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-23 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20171022_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Contact name for bidder questions', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='contact_point',
            field=models.CharField(blank=True, help_text='Contact point (e.g., phone or email) for contact', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Lot'),
        ),
    ]
