# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_lot_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='pickup_instructions',
            field=models.TextField(blank=True, help_text='Additional redemption instructions for the lot'),
        ),
    ]
