# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-23 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20171022_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='aquisition_cost',
            new_name='acquisition_cost',
        ),
    ]
