# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_lot_pickup_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='category',
            field=models.CharField(choices=[('C', 'Cabernet Sauvignon'), ('P', 'Pinot Noir'), ('W', 'Other and Mixed Wine'), ('G', 'Golf'), ('E', 'Experiences'), ('O', 'Other (non-wine)')], default='W', max_length=1),
        ),
    ]
