# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_item_item_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='auction_contact_point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='auction_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationform',
            name='auction_contact_point_field',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The Wufoo field ID for this data item', null=True),
        ),
        migrations.AddField(
            model_name='donationform',
            name='auction_provide_contact_field',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The Wufoo field ID for this data item', null=True),
        ),
        migrations.AddField(
            model_name='donationform',
            name='item_description_field',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The Wufoo field ID for this data item', null=True),
        ),
        migrations.AddField(
            model_name='donationform',
            name='logo_field',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The Wufoo field ID for this data item', null=True),
        ),
        migrations.AddField(
            model_name='donationform',
            name='phone_number_field',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The Wufoo field ID for this data item', null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='auction_contact_point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='abbr',
            field=models.CharField(help_text='Abbreviation for use in application', max_length=16, unique=True),
        ),
    ]
