# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-30 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_auto_20171023_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='actual_sale',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='predicted_sale',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
