# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-12 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_auto_20171030_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='category',
            field=models.CharField(choices=[('O', 'Other'), ('W', 'Wine'), ('G', 'Golf'), ('L', 'Beer, Liquor (non-wine)'), ('ST', 'Sports, Tickets'), ('SG', 'Sports, Memorabilia, Giants'), ('S4', 'Sports, Memorabilia, 49ers'), ('SC', 'Sports, Memorabilia, Cal/Stanford'), ('SC', 'Sports, Memorabilia, Other'), ('EV', 'Experiences, Vacation'), ('EL', 'Experiences, Local'), ('R', 'Restaurant')], default='O', max_length=2),
        ),
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=models.CharField(choices=[('W', 'Wine'), ('G', 'Golf'), ('R', 'Restaurants'), ('S', 'Sports'), ('E', 'Experiences'), ('O', 'Other'), ('X', 'Super Silent')], default='O', max_length=1),
        ),
    ]
