# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-12 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_donation_image_upload_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='main_image',
        ),
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/auction/'),
        ),
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/donation/'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/lot/'),
        ),
    ]
