# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-16 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_auto_20171112_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='assigned_to_lots',
            field=models.ManyToManyField(blank=True, to='auction.Lot'),
        ),
        migrations.AddField(
            model_name='donation',
            name='complete',
            field=models.BooleanField(default=False, help_text='Whether this donation has been received and assigned'),
        ),
    ]
