# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_auto_20180115_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='slide_background',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/auction/'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_primary',
            field=models.ForeignKey(help_text='Person to list on the auction receipt as follow-up contact for any issues', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='auction',
            field=models.ForeignKey(help_text='The auction currently associated with the donation', on_delete=django.db.models.deletion.PROTECT, to='auction.Auction'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='source_form',
            field=models.ForeignKey(help_text='The donation form', null=True, on_delete=django.db.models.deletion.PROTECT, to='auction.DonationForm'),
        ),
        migrations.AlterField(
            model_name='item',
            name='donation',
            field=models.ForeignKey(blank=True, help_text='The donation form submitted for this item', null=True, on_delete=django.db.models.deletion.PROTECT, to='auction.Donation'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auction.Lot'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='auction',
            field=models.ForeignKey(help_text='The auction this lot is associated with', on_delete=django.db.models.deletion.PROTECT, to='auction.Auction'),
        ),
    ]
