# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0018_auto_20180206_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='pulled',
            field=models.BooleanField(default=False, help_text='The item has been removed from the auction'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.CharField(choices=[('O', 'Other'), ('W', 'Wine'), ('WT', 'Wine, Tasting'), ('WL', 'Wine, Large Format'), ('WU', 'Wine, Unique'), ('WM', 'Wine, Mixed Lots'), ('G', 'Golf'), ('L', 'Beer, Liquor (non-wine)'), ('ST', 'Sports, Tickets'), ('SG', 'Sports, Memorabilia, Giants'), ('S4', 'Sports, Memorabilia, 49ers'), ('SC', 'Sports, Memorabilia, Cal/Stanford'), ('SC', 'Sports, Memorabilia, Other'), ('EV', 'Experiences, Vacation'), ('EL', 'Experiences, Local'), ('R', 'Restaurant')], default='O', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(choices=[('OFFICE', 'Guardsmen Office'), ('SFWC', 'SF Wine Center'), ('OTHER', 'Other'), ('ELECTRONIC', 'Electronic'), ('PICKUP', 'Pickup Required')], default='OTHER', help_text='Where the item is currently located', max_length=40),
        ),
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=models.CharField(choices=[('W', 'Wine'), ('G', 'Golf'), ('R', 'Restaurants'), ('S', 'Sports'), ('E', 'Experiences'), ('O', 'Other'), ('X', 'Super Silent')], default='O', max_length=2),
        ),
    ]
