# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-07 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0019_auto_20180405_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='extra',
            field=models.PositiveSmallIntegerField(default=0, help_text='Extra inventory of the item for possible doubling'),
        ),
    ]
