# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.IntegerField(db_index=True, unique=True)),
                ('type', models.CharField(choices=[('L', 'Live'), ('S', 'Silent')], default='S', max_length=1)),
                ('short_desc', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('title', models.CharField(max_length=50)),
                ('restrictions', models.CharField(blank=True, max_length=140)),
                ('reviewed', models.BooleanField(default=False, help_text='The lot has been reviewed for accuracy by an auction chair')),
                ('received', models.BooleanField(default=False, help_text='The auction committee is in possession of all items in the lot')),
                ('confirmed', models.BooleanField(default=False, help_text='The items has been reviewed complete and available on-site for sale')),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=50)),
                ('size', models.CharField(default='750 ml', max_length=10)),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('rating', models.CharField(blank=True, max_length=10)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots.Lot')),
            ],
        ),
    ]
