# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=140)),
                ('onsite_pickup', models.BooleanField(default=True)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_point', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='FMV',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='cost',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='predicted_sale',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='description',
            field=models.TextField(blank=True, help_text='A long description suitable for printed text (e.g. website, program)'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='short_desc',
            field=models.CharField(blank=True, help_text='A short description for a slide or card', max_length=140),
        ),
        migrations.AddField(
            model_name='item',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots.Lot'),
        ),
    ]
